### ISSUE TITLE
Small issues

### ISSUE THREAD

**Issue by hvolschenk** [hvolschenk/iamcare-legacy#102]
A collection of small usability issues:

* [x] Show clickable _Location_ on `/items/{itemID}` page. Will search on click (#104).
* [x] On `/items/{itemID}` page on mobile: Make "contact giver" button `fullWidth`.
* [x] Logo. It's time (#109).
* [x] Scroll to top on navigate (#113).
* [x] On `/items/{itemID}` page, show clickable _User_ (giver) information (#103).
* [x] When loading a URL which is not `/`, a `404` is displayed (#105) (#106) (#107).
* [x] On `/items/{itemID}` page, add "share" action (#108).
* [x] The overflow menu on `/user/{userID}/items` needs to be removed/disabled when not the owner (#112).
  * Maybe on this page the items should be displayed as cards (`ItemCard`) in this scenario.
* [x] When on `items/itemID` (logged out), then clicking on "contact giver", then logging in as the owner, it is possible to contact yourself (#111).
  * Also remove the ability to contact yourself generally.
